### ISSUE TITLE
 Controller settings in var.env have no effect 

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#104]
[Build]
docker 17.7 2018/06/11

[Steps to reproduce]
var.env:
edit the "Controller settings" : CONTROLLER_ORG_ID. Do not user the default PLATTFORM_OPERATOR
stop docker container
start docker container
[Expected result]
I can see the changes in the bssapp db and in the APP Controller
[Observed result]
login to APP Controller. The CONTROLLER_ORG_ID is still "PLATTFORM_OPERATOR"

**Comment by ghost** [comment]
What are the exact steps you have taken regarding `stop docker container` and `start docker container`?

`.env` and `var.env` files are only used during the initial start of the application when using `oscm-deployer` container. In order to see the changes whole oscm instance should be stopped and restarted using `oscm-deployer`.

**Comment by elfriedegoetz** [comment]
for start/stop I used this:
docker-compose -f docker-compose-oscm.yml stop 
docker-compose -f docker-compose-oscm.yml up -d

**Comment by ghost** [comment]
In that case everything works as intended. All `var.env` variables that are stored in the DB are only picked up by the initdb container during initial database setup. Restart will not update the database.

**Comment by elfriedegoetz** [comment]
okay
