### ISSUE TITLE
cannot activate services after creation

### ISSUE THREAD

**Issue by doreilly257** [servicecatalog/oscm#1055]
**Version Info**
v19

**Describe the bug**
cannot activate services for a marketplace.

**How to Reproduce**
create a marketplace
create a technical service
create a marketable service
create a price model
define publishing options
activate or deactivate services - check box "active" and "in catalog"
click and get red error "The operation failed"

**Observed behavior**
error "The operation failed"

**Expected behavior**
service is activated and visible in the catalog

**Screenshots**

**Additional context**
[Stack trace after trying to activate the service](https://app.zenhub.com/files/108258123/5b54d017-b45c-4029-aa27-4671957f286f/download)

**Comment by Piotr-K8i** [comment]
Hi @doreilly257,

Can I ask you to send me detailed information on how you defined the service? If it was created by the "Register service definition" tab, I would ask you to send what "Access type" was selected and what data was entered there. If the service was imported, I would ask you to attach an example xml file.

Piotrek

**Comment by doreilly257** [comment]
It was defined as a Direct Service, I have recreated with External and it now works.

**Comment by Piotr-K8i** [comment]
Thank you for your answer,
The error was probably displayed because there was no connection to the "Provisioning URL".
According to the documentation: 
"**_Provisioning service URL (all access types except external access): URL of the WSDL document that defines the provisioning service you implemented for your application. The Provisioning service URL corresponds to the provisioningUrl attribute in the technical service definition XML file._**"
