### ISSUE TITLE
Fix Stacktrace Exceptions of Birt Report Engine

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1114]
**Summary**
In case a Stacktrace Exception has already occurred in BIRT for any reason, the report engine cannot work anymore and no more reports can be displayed.

**Details**
If it cumbersome to work with BIRT in case an exception has already occurred (for example when showing a Report for a non-existing key). The next times the user want to display correct reports it is not possible (for example Billing report of a supplier for a correct organization Id). 
This reduces significantly the User Experience when working with Reports.

**Acceptance criteria**
-  [ ] The issue is fixed. 
- [ ] UI Test for Reports? Is this possible?

**Additional context**
N/A.

**Comment by GoebelL** [comment]
@farmakiG 
this issue is unclear and not ready for estimation. Please give precise descriptions. 
If you consider there is a bug, then please use the Bug template. In this case fill in the requested information of steps to reproduce, observed and expected behaviour. Otherwise, if you have a concrete task in mind, for example how to improve the BIRT reports then give some instructions on the work that you consider to be done.

**Comment by farmakiG** [comment]
It was a bug but I am not able to reproduce it anymore. 
In order to reproduce it, I have chosen an invalid month for the Broker/reseller revenue share report, so that an Exception occurs (so a Stacktrace with the Exception is shown instead of the report), and then I selected one of the other reports (e.g. Customer Report of a supplier) and an error screen with a Stacktrace (but without exception cause) still appeared. 
Maybe the reason for this occurrence  had to do with my private build.
