### ISSUE TITLE
Security Warning for Birt Report Engine

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1115]
**Summary**
A security warning appears for the URL of the Birt Reporting Engine at the attempt to show a Report.
In Chrome it is possible to "Accept the Risk" and proceed to the URL, but in Firefox not. Therefore in Firefox the Reports cannot be displayed properly.

**Acceptance criteria**
- [ ] Solution for Firefox for enabling the option to proceed to the unsafe URL, just like in Chrome.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
This works as expected. The browser warns on the selfsigned certificates. You need to obtain and import a valid SSL certificate for your OSCM host domain in OSCM. The detailled procedure is described in the Getting Started Guide.
In order to work with the self-signed certificates, e.g. for example in staging invironments, you need to accept such warnings. Just open a new browser tab and copy the URL displayed in the BIRT Iframe from the report dialog into the location bar in the new tab. Then your browser will give you the button that lets you to bypass and accept with the unsecure certificate.
