### ISSUE TITLE
Azure VM template

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1154]
**Summary**
Provide an Azure VM template for OSCM

**Details**
- [ ] Investigate VM options to setup OSCM with cloud init.
- [ ] Test the installation in Azure with respective user

**Acceptance criteria**
- [ ] Possible error cases are handled with clear messages and error return code
- [ ] Secure and GBDR conform system logging
- [ ] OSCM required runtime is available after VM creation (docker, docker-compose....) 

**Additional context**
Ask me

**Comment by Piotr-K8i** [comment]
This task is closed, due to the creation of another task in which the "Azure VM" and "AD tenant" scripts will be transferred and tested to/in the dockerbuild repository [Add scripts for setup with OIDC](https://app.zenhub.com/workspaces/oscm-59f31a4996b6c551bc556610/issues/servicecatalog/oscm-dockerbuild/321)
