### ISSUE TITLE
Help button on marketplace taskbar does not work

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#1165]
**Version Info**
19.0 2021/01/19

**Describe the bug**
Help button on marketplace taskbar does not work

**How to Reproduce**
1. login as supplier on oscm-portal
2. goto marketplace
3. click "Help" on taskbar but nothing happens

**Screenshots**
![escm1](https://user-images.githubusercontent.com/15209605/105472415-32b04b00-5c9c-11eb-83aa-4314a8bf6557.PNG)

**Comment by Piotr-K8i** [comment]
I tested what could be the cause. The "Help" button does not work on the default port. It works on port 8081.
@GoebelL  could you please tell us how are we to deal with this bug?

**Comment by GoebelL** [comment]
Hi @KabacinskiPiotr @elfriedegoetz 
The cause of this bug is that the proxy rule for 'oscm-portal-help' is missing in the nginx configuration.
As workaround you can add it in the file on your host. 
```
vi /docker./config/oscm-proxy/data/proxy.conf

```
Insert following section behind the 'location /portal { ... }' rule:
```
location /oscm-portal-help {
   proxy_pass https://oscm-core:8081/oscm-portal-help/;
   proxy_set_header Host            $host;
   proxy_set_header X-Forwarded-For $remote_addr;
   client_max_body_size 50m;
}
``` 
Restart the proxy 
```
docker-compose -f ./proxy/docker-compose-proxy.yml restart
``` 
@KabacinskiPiotr 
Of course the proxy has to work out of the box. Therefore a fix is needed. In order to make this permanent, the rule has to be inserted  [here in the proxy.conf.template](https://github.com/servicecatalog/oscm-dockerbuild/blob/master/oscm-deployer/resources/proxy.conf.template#L39).

**Comment by elfriedegoetz** [comment]
help works fine with 19.1 2021/01/27
