### ISSUE TITLE
Saving the user profile in the marketplace UI shows error 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1210]
**Version Info**
v19.1 latest (10/03/2021)

**Describe the bug**
There is an operation failed error on saving profile, in case the user does not have administrative permissions.
Saving the profile works well for the default users in  the sample data, due to their administrator role.
 
**How to Reproduce**
1. Create a user without roles
2. Login to marketplace portal as **user without any roles**
3. Goto account > profile
4. Change user data and save
5. See error

**Expected behavior**
Saving is successful

**Observed behavior**
Operation failed error

**Screenshots**
N/A

**Additional context**
Ask me

**Comment by Piotr-K8i** [comment]
The problem also occurs at  marketplace/account/editGroup.jsf and operator/createOrganization.jsf

**Comment by Piotr-K8i** [comment]
The problem occurs only for Sample Data, otherwise the UI tests would also not pass

**Comment by Piotr-K8i** [comment]
The problem is incorrect configuration of the var.env file:
PROXY_HTTP_HOST = proxy.
SMTP_FROM = oscm@estessbesci11. 

Since the change [Clean up scripts (#40)](https://github.com/servicecatalog/oscm-jenkinsscripts/commit/65bec67b3cd61e8116c9c037fcb7311f948c1582) the DOMAIN parameter should also be passed along with the appropriate value 

After restarting the Pull&Start script, the var.env file is configured correctly and the error does not appear
