### ISSUE TITLE
Limit number of free of charge deployments

### ISSUE THREAD

**Issue by fabiorauber** [servicecatalog/oscm#126]
I was searching for a way to limit the number of free of charge software subscriptions, for example, to limit each customer to 1 active free of charge marketable service subscription. I couldn't find a way to configure this on OSCM. Is there such a feature?

**Comment by GoebelL** [comment]
Hi @fabiorauber 
Well, for services with access type LOGIN, you can limit the number of registered users per subscription and also the number of concurrent users. I don't know if this is helpful for your case. Otherwise I could think of a solution with a create subscription trigger that checks the number of existing subscriptions and compares this with a given limit parameter.

**Comment by fabiorauber** [comment]
Hi @GoebelL, thanks for the help. But please correct me if I'm wrong, apparently there is no way of forbidding the customer to change the triggers, so, in theory, the customer could create as many subscriptions as wanted, as long as he deletes the "check availability" trigger. Maybe a "items in stock" field in each marketable service would be helpful in this and maybe other cases?

**Comment by GoebelL** [comment]
@fabiorauber, you are right, the customer administrator can remove triggers. I see two options to limit the subscriptions.

1. The direct and easiest way would be to use the LOGIN access type as described before. See [Technology Provider's Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/TechProv.pdf), chapter 2 for details. This allows the service manager to specify the predefined parameter "Maximum number of registered users for a subscription" (`NAMED_USER`) individually for the free and for the payed marketable services he provides to his customers.
![max_reg_users](https://user-images.githubusercontent.com/14805690/43205465-b94aef64-9023-11e8-976d-db977b079150.png)
2. Another idea which comes in my mind:  You could enhance your technical service implementation in order to track its created instances. I.e. define an integer service parameter `MAX_NOF_SUBSCRIPTIONS`  with some default value in your technical service XML template. You can implement the check with a few code lines in your provisioning service (implementing [asyncCreateInstance](https://github.com/servicecatalog/oscm/blob/master/oscm-extsvc-provisioning/javasrc/org/oscm/provisioning/intf/ProvisioningService.java)). 
Count the instances, compare with your service parameter MAX_NOF_SUBSCRIPTIONS given with the InstanceRequest and decide to either complete or abort the provisioning with return of an respective error message.

**Comment by GoebelL** [comment]
@fabiorauber 
Does it work for you?

**Comment by fabiorauber** [comment]
@GoebelL, we will try the second approach, I think will work for our use case. Nonetheless, I still believe the best way to solve this problem would be to implement some kind of limit on the marketable service itself, preventing the user from ordering the service beyond certain limit. Don't know the difficulty of such implementation though.
