### ISSUE TITLE
Provide a XaaS connector with flexible script based provisioning

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#158]
Need a generic APP v2 controller which allows shell based remote provisioning on any hypervisor.

**Comment by uhu133** [comment]
I see the following enhancements regarding the existing Powershell connector. Please consider them.
1. The new connector shall use Json as return format from script to connector (instead of plain text)
-> https://github.com/servicecatalog/oscm-app-shell/issues/9
2. The new connector shall provide an additional script. This script is called regularly to collect billable events (similar to OpenStack connector)
-> https://github.com/servicecatalog/oscm-app-shell/issues/15
3. The new connector shall pass all UDAs (if set) to all scripts 
-> https://github.com/servicecatalog/oscm-app-shell/issues/10

**Comment by kowalczyka** [comment]
The question is also what types of scripts should be handled? 

What do we mean by "flexible script based provisioning"?

**Comment by uhu133** [comment]
I would prefer bash scripts. Starting from them I could call any thing else. Flexible means that it can be scripted without coding. But maybe this is not the right wording.

**Comment by uhu133** [comment]
One further item: 
4. The new connector shall receive the access info from the provisioning script as return value
-> https://github.com/servicecatalog/oscm-app-shell/issues/11

**Comment by GoebelL** [comment]
Point 2 is for later as it requires some basic refactoring.

Further requirement points discussed:

5. The new connector shall provide details in custom tab
-> https://github.com/servicecatalog/oscm-app-shell/issues/13
6. The new connector shall provide for basic validation 
-> https://github.com/servicecatalog/oscm-app-shell/issues/14
7. The new connector shall provide for logging of in-bound and out-bound data
-> https://github.com/servicecatalog/oscm-app-shell/issues/12 
8. The new connector shall access the scripts on defined mount point in APP container
-> https://github.com/servicecatalog/oscm-app-shell/issues/6
9. The new connector is deployed with APP docker build
-> https://github.com/servicecatalog/oscm-app-shell/issues/2

**Comment by GoebelL** [comment]
Respective development task issues will be attached to this epic.
