### ISSUE TITLE
Azure Controller: How to ensure client_id and client_secret are stored encrypted

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#166]
[Build]
docker 2018/10/23
[Expected result]
these should be stored encryptedin the bssapp datastore according to the other controllers
[Observed result]
unencrypted in bss datastore

**Comment by GoebelL** [comment]
Those secrets should be declared as password type parameters in the technical service XML. These are string parameters ending with "_PWD", like for instance [this one](https://github.com/servicecatalog/oscm/blob/master/oscm-app-vmware/resources/TechnicalService_VMware.xml#L324).

**Comment by ghost** [comment]
From what I have checked it appears that `_PWD` suffix only changes the type of input field in the UI so it is masked and can not be read from the UI. It does not change in any way how the values are stored both in bss and bssapp databases. They are still a plain text values.

UI
![image](https://user-images.githubusercontent.com/40793157/47650036-4fbe4800-db7f-11e8-92a0-92c0e8631d45.png)

DB
![image](https://user-images.githubusercontent.com/40793157/47650125-90b65c80-db7f-11e8-9ffa-a0fdeae553c8.png)

> these should be stored encrypted in the bssapp datastore according to the other controllers

Actually, the "expected result" is inaccurate because other controllers do not use subscriptions to pass this kind of data. They are stored as controller attributes in different tables.

**Comment by GoebelL** [comment]
@fest-floreks 
First, you are right that the _PWD suffix is for masking the values on the UI only. However, if you'd dig a bit deeper you would find that the parameter encryption _is implemented_ in the provisioning API in OSCM. [Service parameters of password type are stored encrypted](https://github.com/servicecatalog/oscm/blob/master/oscm-domainobjects/javasrc/org/oscm/domobjects/Parameter.java#L147). When [OSCM creates the instance request](https://github.com/servicecatalog/oscm/blob/master/oscm-application/javasrc/org/oscm/applicationservice/bean/ApplicationServiceBean.java#L557) it [prepares the service parameters with handling encryption](
https://github.com/servicecatalog/oscm/blob/master/oscm-application/javasrc/org/oscm/applicationservice/filter/ParameterFilter.java#L74).
APP processes the description from the instance request and [stores the instance with encrypted parameter](https://github.com/servicecatalog/oscm/blob/master/oscm-app/javasrc/org/oscm/app/v2_0/service/AsynchronousProvisioningProxy.java#L151).
The service instance parameters [are decrypted when creating the provisioning settings](https://github.com/servicecatalog/oscm/blob/master/oscm-app/javasrc/org/oscm/app/domain/ServiceInstance.java#L448) which passed to the controller. 

 I believe the only thing that is missing here is the definition of the parameter type as PWD.  
```
<ParameterDefinition ... id="CLIENT_ID_PWD" valueType="PWD">
```
