### ISSUE TITLE
Wrong path for branding package in Operator's Guide

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#194]
**Version Info**
OSCM 17.8 documentation
 
**Describe the bug**
Operator's Guide, Chapter 9.5 point 3: The target path for the branding package is wrong.

**Observed behavior**
"Put the .tar.gz file into the following directory on your Docker host:
/docker/config/oscm-branding/brandings"

**Expected behavior**
"Put the .tar.gz file into the following directory on your Docker host:
/docker/config/brandings"

**Comment by cworf91** [comment]
In the documentation the Chapter 9.5 point 4: The steps a, b and c are unnecessary. 
Under the step f it musst be called folder, not tar.gz.

In the Induroduction of the Chapter 9.5 there is no longer a need for creating a tar.gz. Now the user has to put the files in a folder, therefore point 2 is unnecessary as well. 

In addition to the changes listed under point 3, "put tar.gz" must be changed to "put the folder".

**Comment by gertipoppel** [comment]
**Version Info**

OSCM 17.9 documentation

**Fix**

Changed the description in Operator's Guide 9.5 as well as in the online help page "Customizing the marketplace layout" (called when clicking ? on the Customize Layout page in the portal.

Fixed by commit https://github.com/servicecatalog/documentation/commit/14579f4b674125d672739c6a10895992733d1097
