### ISSUE TITLE
Localized text not visible on AWS provisioning errror

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#214]
**Version Info**
17.0
 
**Describe the bug**

On failed provisioning of a VM (in this case the security group did not exist in AWS) the following mail was sent:
---------------------
Dear Mr. X,

The subscription 'AWS_EC2 v2.0(4)' for the customer with the ID '959c9bf7' could not be activated. The service instance could not be provided. 

[org.oscm.app.v2_0.data.LocalizedText@50502f63, org.oscm.app.v2_0.data.LocalizedText@74bcb1d4, org.oscm.app.v2_0.data.LocalizedText@188b60d5]escm

With best regards. 

This email has been automatically generated. Please do not reply to this email.

---------------------

The localized text shall be visible to describe the error.

**Comment by Crystalzord** [comment]
Hello. 

I wonder - how could I reproduce this bug?
Because whenever I try to set a security group to a non existing one, or to any existing one, the service seems to ignore it and it sets the security group to default anyway.
Example setting:
![aws-bug-localized-setting](https://user-images.githubusercontent.com/19170783/55396297-de2a6180-5543-11e9-8612-4a442f28802b.PNG)

Logs suggest that there was no security group given:
![aws-bug-localized-logs](https://user-images.githubusercontent.com/19170783/55396310-e6829c80-5543-11e9-81f4-e5997a9923e6.PNG)

In the end, the instance is provisioned with default security group...
![aws-bug-localize-default-anyway](https://user-images.githubusercontent.com/19170783/55396340-f9956c80-5543-11e9-8612-0a209828117d.PNG)

**Comment by uhu133** [comment]
Problem still exists.

let's have a telco to investigate
![image](https://user-images.githubusercontent.com/32158057/55490586-4a848e00-5634-11e9-99f2-02f7642e1e1e.png)

**Comment by Crystalzord** [comment]
Fixed in commit https://github.com/servicecatalog/oscm/commit/0a5d229f2110e9214635d1d6d93b5585692d8b68
