### ISSUE TITLE
Prevent forms from resubmission after refreshing the page

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm#234]
**Summary:**

On pages that are designed with use of *form* tags, user is promted to resubmit form content.
In some cases that may result with exception being thrown (ex. oscm-app/default.jsf).
It is advised to either redesign the forms to use JS onclick actions rather than submit buttons or introduce navigation rules that will redirect user to the same page.

**Acceptance criteria:**
- [ ] when page with form (like controller's UIs) is refreshed after submitting the changes, message to confirm form resubmission does not appear

**Details:**
- proposed solution is to add navigation rules to *faces-config.xml*. For example:

![obraz](https://user-images.githubusercontent.com/47355402/53495304-f66c1400-3a9f-11e9-9459-40f34311d332.png)

**Comment by GoebelL** [comment]
The described here is the currectly implemented solution for a list of JSF views in OSCM. However this is a bit brittle, since there is no suitable measure to ensure that this list is complete. 
I am convinced we'll find a generic solution, that can be better applied to the UI as whole. For example, this might be to put some servlet filter in front which implements the post-redirect-get pattern.

**Comment by GoebelL** [comment]
... of course a generic solution requires some attention on the system performance.

**Comment by GoebelL** [comment]
Not such resubmission releated issues have been reported in past time and this request is of low priority. Therefore we have dropped plans for launching the described implementation. Feel free to reopen if you experience any issues.
