### ISSUE TITLE
Google code formatter behaves not as expected

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#264]
**Version Info**
Latest

**Describe the bug**
Automatic google code formatter is not working as expected.

**How to Reproduce**
1. Check the commits: https://github.com/servicecatalog/oscm/commits/task/synchronize_credentials
2. No code formatting after https://github.com/servicecatalog/oscm/commit/9a563f0bfaca9cfc5660e0d816f7e3b32d64cb7e
3.  Strange behaviour in comit: https://github.com/servicecatalog/oscm/commit/6be5a94d883b08442103b933828c41b2dbd04088

**Observed behavior**
Formatter did not format the code nor add the header (pasted java code instead)

**Expected behavior**
Formatter only formats the code and add missing header.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by GoebelL** [comment]
@kowalczyka 
Ok, good found. As for the time beeing I suggest to revert this code formater from master in order to avoid further mess. 
Furthermore the given travis results also indicate that `testIsContainCopyrightHeader` is missing some adaption, because having this code formatter the Java files would be pushed without copyright header.

**Comment by adamczykba** [comment]
@GoebelL @kowalczyka 
Would it be fine to just disable the travis stage until issue is fixed?

**Comment by adamczykba** [comment]
@GoebelL 
Format step is currently commented out to avoid futher mess

**Comment by GoebelL** [comment]
Thanks.
