### ISSUE TITLE
Technical Concept

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#318]

**Comment by farmakiG** [comment]
**Allow the approval of trigger processes for Suppliers.**

Enhance the OSCM internal interface and the portal in order to allow the approval of waiting customer subscriptions of suppliers. 
The supplier will be allowed to define a "Subscripbe to Service" trigger type as well as to approve waiting subscriptions. The UI will be extended with an extra button "Approve" in the processes page and possibly an "Approve Subscription" page in the classic portal.
