### ISSUE TITLE
How can help and report labels be modified?

### ISSUE THREAD

**Issue by gertipoppel** [servicecatalog/oscm#41]
I want to add customized help files or report labels in OSCM. How can this be achieved? The "old way" is described in the Operator's Guide, Appendix E

**Comment by shimizuf** [comment]
Hi @gertipoppel.

Regarding customized help files, there is an open issue here: servicecatalog/oscm-dockerbuild/issues/65. Basically it will be possible to create archives containing the customized help files and mount them into the online help container, which will then provide/serve them.

As for custom report labels, I'll create an issue in servicecatalog/oscm-dockerbuild since it's an enhancement of the container functionality.

**Comment by shimizuf** [comment]
Issue regarding custom reports: servicecatalog/oscm-dockerbuild/issues/76

Closing as duplicate.
