### ISSUE TITLE
LOG_LEVEL configuration setting not working

### ISSUE THREAD

**Issue by grubskim** [servicecatalog/oscm#50]
Changing LOG_LEVEL does not have any effect on the log output.

How to reproduce:
Change LOG_LEVEL to, for instance OFF - expecting no log output. Relog the user. The information "user logged in" will be shown in log.

**Comment by gertipoppel** [comment]
Are there additional log levels now? INFO, DEBUG, WARNING were the ones.

**Comment by shimizuf** [comment]
@grubskim If I recall correctly the LOG_LEVEL Docker variable may only have effect in the initdb container, i.e. as a config setting for the database initialization. It may not have any effect if set for the application containers (core, app, ...).

**Comment by grubskim** [comment]
Should this setting be editable at all then? @shimizuf @GoebelL

**Comment by shimizuf** [comment]
I see two aspects here.

In principle it is already editable because it is a variable in the initdb image. And it will be set in the respective property files for db initialization. See for example configsettings.properties.core.template. But the functionality must be tested.

Another question is whether we want to expose the setting in the Docker Compose templates. At the moment it's not present in the Docker Compose files, which means the default set in the Dockerfile is used, but it can already be manually added to the Docker Compose file by an operator.

**Comment by GoebelL** [comment]
>Another question is whether we want to expose the setting in the Docker Compose templates. 

Beside of initdb, we need at least to carry out the log levels for core and app containers. I guess it's less effort to just allow and propagate this setting with Docker Compose files than to describe in the Operator's Guide how to configure it manually. So, please go ahead and expose it.

**Comment by grubskim** [comment]
Exposed LOG_LEVEL in docker compose in [this commit](https://github.com/servicecatalog/oscm-dockerbuild/commit/18260628d9acd91dc84f7be954a44aa38e0e64f4). The default value is INFO.
