### ISSUE TITLE
No default entries for AWS in app configurationsetting table although aws controller is deployed

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#58]
[Version] OSCM 17.5.0 2017/11/29

[How to reproduce]

Login to app controller /oscm-app/

[Expected result]
In table are two "Controller ID" by default
- for Openstack
- for AWS

[Observed result]
There is only one controller: for Openstack

[Details]
I remember the problem. It was related with https://github.com/servicecatalog/development/issues/866 but then it was repaired. The problem got back in today's build.

**Comment by shimizuf** [comment]
For a fix I propose that we remove the variable CONTROLLER_ID from var.env and move it to the specific containers in docker-compose-initdb.yml[.template]. In docker-compose-initdb.yml[.template] the container oscm-initdb-controller-openstack should have a variable of CONTROLLER_ID=ess.openstack, and analogous for the aws controller container. In that way we can initialize both controller databases with minimal effort.

The only disadvantage I see with this approach is that because both containers share the other variables in the var.env file, they will always have the exact same settings for CONTROLLER_ORG_ID, CONTROLLER_USER_KEY, etc.

**Comment by badziakp** [comment]
Issue fixed in oscm-dockerbuild repo
