### ISSUE TITLE
[sso] multi tenant: login of supplier organization to portal does not work

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#580]
**Version Info**
sso build from 12/11/2019

**Describe the bug**
login is redirected to the wrong tenant.

**How to Reproduce**
1. login to CTMG as administrator and create a new tenant "abc" . A corresponding tenant exists in azure. The app registration was performed. A user "xxx" exist in azure for this tenant. 
2. create a new organistaion with administrator "xxx"
3.  From CTMG log out as administrator 
4. login to  CTMG as "xxx" for the tenant "abc" .
   https://<host>:<port>/oscm-portal/?tenanID=b62a5828

**Observed behavior**
login is redirected to the default tenant

**Expected behavior**
login is redirected to the tenant "abc"

**Comment by GoebelL** [comment]
In your described scenario, the user "xxx" is a customer and therefore not allowed to access the administrator portal. 
The user has to be redirected to his marketplace. And if setup is correct, his marketplace should belong to the custom tenant.

@elfriedegoetz 
Short questions
a) Is the user redirected to the marketplace? 
b) How did you verify "login is redirected to the default tenant"?

**Comment by GoebelL** [comment]
I have retested the given case myself. I confirm that current behavior works as designed but can be improved. In any case this issue is not a login blocker and thus the given title is not justified.

In step 4 a user has logged in at OIDC side, who has no access rights in OSCM to visit the administrator portal. Therefore the filter redirects to that marketplace landing page, which the platform operator has defined in the configuration settings in MP_ERROR_REDIRECT_HTTPS. This redirect URL is not tenant specific. An URL of a public default tenant marketplace is expected here.

This is exaclty same behavior as in previous SAML based versions 17.4 and before.

**Comment by GoebelL** [comment]
Request for improvement:
After login at OIDC provider side and detecting missing manager role for accessing the adminstrator portal the user shall be redirected to the tenant marketplace of his organization.

**Comment by elfriedegoetz** [comment]
In the scenario the organization is a Supplier Organization, therefore the admin of this organization should have access to the portal.
@GoebelL 
your question:
  a) Is the user redirected to the marketplace?
![NewTenant](https://user-images.githubusercontent.com/15209605/70040194-68d3cc80-15bb-11ea-9c6c-f4daadcc4060.PNG)


the user is redirected to azure see attachment
  b) How did you verify "login is redirected to the default tenant"?
see attachment
![NewTenant2](https://user-images.githubusercontent.com/15209605/70040080-375b0100-15bb-11ea-9a9d-0dafab7ea43e.PNG)

In my scenario it is the default tenant

**Comment by cworf91** [comment]
I have also retested this scenario. The multitenant login works the way it should. I was able to reconstruct the described error with the following scenarios.
1. The url https://:/oscm-portal/?tenanID=b62a5828 is wrong like https://:/oscm-portal/tenanID=b62a5828
2. The tenandID does not exist
3. The tenant has no configuration
However, this looks more like a configuration or user issue.
