### ISSUE TITLE
Bad help link 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#60]
version: 
v17.5.0 (2017-12-05) 

How to reproduce:
login as administrator to OSCM portal. Open manage users page and click help link.

Expected:
Manage users help page opens in separate tab.

Observed:
HTTP Status 404 - /oscm-portal-help/help/en/help/tasks/operator_manageConfiguration.htm/help/en/help/tasks/operator_manageLdapSettings.htm/help/en/help/tasks/operator_manageUsers.htm/help/en/help/tasks/operator_manageConfiguration.htm/help/en/help/tasks/operator_manageUsers.htm

**Comment by GoebelL** [comment]
Additional  info:
The help link is correct for the first landing page, which opens directly after login. But once I click in the menu the help link URL in the opened page becomes a 404 pointer, messed up from somehow differently concatenated help links.

**Comment by grubskim** [comment]
Fixed now in master. The reason was incorrect URL caching - now the only part cached is the base.
Please note that HELP_URL, to work correctly, should end with "oscm-portal-help", or be left empty (right now we are deploying help in two places, and this will cause to use the oscm-core container version). Also, after changing the HELP_URL, relogging is required.

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/12/06. Now online help works as expected, with HELP_URL and also without it.
