### ISSUE TITLE
log files in docker directory

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#65]
[Build] 17.5+ 2017/12/11
Question:
Why are the log files under docker/logs/\<container-name\>/*.log empty?
-rw-r----- 1 root root 0 Dec 11 10:11 logs/oscm-app/oscm-app.out.log
-rw-r----- 1 root root 0 Dec 11 10:11 logs/oscm-birt/oscm-birt.out.log
-rw-r----- 1 root root 0 Dec 11 10:11 logs/oscm-branding/oscm-branding.out.log
-rw-r----- 1 root root 0 Dec 11 10:11 logs/oscm-core/oscm-core.out.log
-rw-r----- 1 root root 0 Dec 11 10:11 logs/oscm-db/oscm-db.out.log
-rw-r----- 1 root root 0 Dec 11 10:11 logs/oscm-help/oscm-help.out.log

**Comment by shimizuf** [comment]
The log files are created as empty files by the deployer. But they are not used, unless you configure docker-compose and syslog on your Linux server to write the container logs to these files instead of the default Docker log storage (which is accessed with `docker logs`).

I believe it's possible to only have the deployer create these empty files if they are actually desired - that is, if the deployer is started with `SYSLOG=true`. This would be en enhancement in oscm-dockerbuild.

**Comment by ghost** [comment]
Thanks! @gertipoppel this should be also documented
