### ISSUE TITLE
"The operation failed." message after activated service

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#683]
**Describe the bug**
**"The operation failed."** message after activated service, no status change to active

<<<<<<<<<<<<<<<<<************Stacktrace************>>>>>>>>>>>>>>>>>>
ERROR: ThreadID https-jsse-nio-8081-exec-10: ExceptionActionListener: ?? key 'ERROR' not found ??
javax.faces.FacesException: #{bean[action]}: java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)

<<<<<<<<<<<<<<<<<************UPDATE************>>>>>>>>>>>>>>>>>>
After clicking on the field next to the checkbox and accepting the changes, a message about changing the service is displayed
![image](https://user-images.githubusercontent.com/59691196/75338870-bf396a00-588f-11ea-8ad8-fde751044d9f.png)

**How to Reproduce**
1. Go to **'oscm-portal/service/activation.jsf'**
2. Mark **"Activate" checkbox for service**
3. Click on **'Save' button**
4. See **error**

**Observed behavior**
After adding a few services and trying to change the status of the service to active, the message "The operation failed" appeared at the top of the page. 

**Expected behavior**
1. After click "Save" button selected service/services should be activated
2. The content of the message should be "The activation state of the services has been successfully saved"
3. Checkbox at the "Active" column should be marked

**Screenshots**
![image](https://user-images.githubusercontent.com/59691196/75332977-97450900-5885-11ea-92ea-ded3e0a91091.png)

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
As far as I can see, the here reported Operation Failed error is a subsequent issue due to a bad error handling. 
The causing error is written in the system.log:
02/25/2020_09:36:45.829 FSP_INTS-BSS: WARN: ThreadID https-jsse-nio-8081-exec-9: ServiceProvisioningServiceBean: 40190: _The technical service Service Name is currently not available._
org.oscm.internal.types.exception.TechnicalServiceNotAliveException: EXCEPTIONID 1582623405829: SUPPLIER
In fact, in case the service is not available,  instead of the 'operation failed' screen only the italic marked error message has to brought to the UI. The respective error handling might have been broken through the bootsfaces refactoring.

**Comment by Piotr-K8i** [comment]
The default value should be entered
"http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl" 
I think we should consider to simplify OSCM application: [#1056](https://app.zenhub.com/workspaces/oscm-59f31a4996b6c551bc556610/issues/servicecatalog/oscm/1056)
