### ISSUE TITLE
app communication is not secure

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#71]
[Build] 17.6 

[Steps to reproduce]

1.  import aws technical service using provisioning url:
https://estst1.intern.est.fujitsu.com:8881/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl
2.  see if service is available
3. check if http provisioning URL is available 

[Expected result]
2. service is available
3. http provisioning URL should not be open (security problem)

[Observed result]
2. service is not available (CN servers for certificate do not match)
3. http provisioning URL is open for provisioning

[Details]
http should not be open for provisioning. We used to have this problem in old versions of ctmg and this was judged as a security problem because there is no authentication used between bes and app. This would mean that any bes instance could access app. This was fixed by using certificates.

**Comment by ghost** [comment]
Issue 2. (service not available) can no longer be reproduced

**Comment by GoebelL** [comment]
@kowalczyka 
Please check the remaining first part:
"1. http provisioning URL should not be open (security problem)"

External access is to be restricted to HTTPS. Please check if the HTTP connector in APP TomEE configuration can be safely removed.

**Comment by kowalczyka** [comment]
Removal of http connector in tomee configuration of app resolves the issue. 

As this container related issue - closing and moving to oscm-dockerbuild repository - https://github.com/servicecatalog/oscm-dockerbuild/issues/105

**Comment by GoebelL** [comment]
HTTP connector is needed for internal communication. HTTP access from outside the container network has to be restricted by other means.

**Comment by shimizuf** [comment]
The concept is that we offer only HTTPS ports to the outside world. Within the Docker network, HTTP ports are still exposed and used for internal communication. This is to eliminate potential problems with host name mismatches in the many different configurations involving SSL certificates, which can also be operator provided.

However, we were exposing HTTP ports to outside. This is now fixed by commits
servicecatalog/oscm-dockerbuild@a882be99b554d52c835b5bce891a11fa2d6b56b2
and
servicecatalog/oscm-dockerbuild@6f71a61d7e0fff98b3c26995d585a17585959d12
