### ISSUE TITLE
Operation failed at marketplace/account/profile.jsf

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#748]
**Version Info**
Version 18.1

**Describe the bug**
"Operation failed" message after attempting to enter marketplace/account/profile.jsf

**How to Reproduce**
1. Go to oscm-portal/marketplace/account/index.jsf
2. Click on Profile -> Show
3. See error

**Observed behavior**
After entered to the profile.jsf page, an error is thrown in the console "Parameter marketplaceId must not be null."

**Expected behavior**
- [ ] The page should load correctly
- [ ] No errors in the console
- [ ] Basic UI tests implemented
- [ ] Create better tests for ManageAttributesCtrl

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/db71a47d-a425-4347-ab51-afdbaf4a81fb)

**Additional context**
[Console errors](https://app.zenhub.com/files/108258123/4a33db79-8e2e-4e61-94c7-42584b31661e/download)

**Comment by GoebelL** [comment]
I can see that [sessionBean.getMarketplaceId()](https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/dialog/mp/attributes/ManageAttributesCtrl.java#L110) in ManageAttributesCtrl#initModel returns _null_ 

Whoops! SessionBean doesn't get initialized properly even when accessing with given marketplace ID in mId URL parameter. Obviously something got broken in the general init flow very recently. This could be caused from header or main templates, or from filter changes. 

This issue is major and needs to be analysed carefully. The init logic is complex and any quick fix may cause more harm. It's probably slipped in very recently. At least the v18.1 tagged commit is definitely still working. This also indicates that we need a UI test here. 

In order to locate the causing code modification, I suggest to checkout the source from a last working state and see what is changed since then.
