### ISSUE TITLE
User is not redirected to HTTPS when it tries to access via HTTP

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/oscm#85]
[Build] 
17.6 2018/02/14 

[Steps to reproduce]
- Try to access OSCM with the same link of 17.4

[Expected result]
- User should be redirected to the new HTTPS port

[Observed result]
- User receives the message that the service is unavailable 

[Details]

![image](https://user-images.githubusercontent.com/24247646/36380124-72c45868-1581-11e8-8526-862c56222a75.png)

**Comment by Crystalzord** [comment]
Hi.
Indeed this issue appears, however this is intentional.
Docker container for oscm-portal access exposes only one port for SSL connection - 8081. 
Http connection is not allowed and since the application is on docker, and the container does not expose any port with http connector, the redirection is not easy to setup.
To do the redirection, we would have to expose a port on the docker container, then a request sent to that port could be processed by tomcat and the request could be redirected to a different (https in this case) port. If a port is not exposed, than the request does not even reach Tomcat, and therefore the redirection will not happen.

If anyone would like to have a "pretty" way to access the portal, using for example http://domain-name.com/oscm-portal and expecting this to be redirected to https://, this can be achieved by setting up an Apache HTTP Server in front of OSCM. Apache HTTP Server could than be responsible for the redirections using for example ProxyPass and ProxyPassReverse from mod_proxy module.
