### ISSUE TITLE
Mobile Stage 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#893]
**Summary**
Provide for defining a separate marketplace stage content, that is shown only in mobile view.

**Details**
Marketplace stage dimensions are designed for desktop displays. This is not suitable for small display media. The request is to allow the marketplace owner to define a second stage content that is used for small display views.
Unless a mobile stage is defined a default white label mobile stage shall be shown in a small view (an image created from existing white label stage image with mobile dimensions). 
 
**Technical Implementation**
*Service layer*
Extend `org.oscm.internal.intf.BrandService`
```java
   public void setMarketplaceMobileStage(String mobileStageContent, String marketplaceId,
            String localeString) throws ObjectNotFoundException,
            OperationNotPermittedException;
```

*Data and Persistence Layer*
New enum filed in `org.oscm.domobjects.enums.LocalizedObjectTypes`
```java
    /**
     * Defines the content of the mobile stage of the landing page.
     */
    MARKETPLACE_MOBILE_STAGE(InformationSource.DATABASE),
```

Data migration is not needed.

**Acceptance criteria**
Two stages can be defined (optional)
- [ ] Mobile stage is shown in mobile view in case if it's defined for the opened marketplace
- [ ] Mobile default stage is shown in small view if mobile stage is undefined
- [ ] Marketplace desktop stage is shown in large views as before

**Additional context**
N/A

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-interfaces/pull/48

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-interfaces/pull/49#pullrequestreview-426147321
https://github.com/servicecatalog/oscm/pull/922#pullrequestreview-426139836

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/923

**Comment by cworf91** [comment]
Due to the changes in this task, the help has to be adapted. My suggestion is:

Customizing the marketplace stage
On the Customize stage page, you can customize the area of the marketplace home page where you can place, for example, advertisements, eye catchers, or further information.
The marketplace stage can be provided as an image or as HTML code linking, for example, to animations. A separate stage **_or mobile stage_** can be used for each of the supported languages. A preview function allows you to view the stage **_or mobile stage_** before it is published. As soon as you confirm the preview, the stage is published and visible to all visitors of the marketplace.
The branding of a marketplace also comprises its layout (colors, fonts, background images, logos, etc.) and the texts (labels of user interface elements, email message texts, etc.). The layout can be customized using the Customize layout menu option in the Marketplace menu. The texts can be customized using the Customize texts menu option in the Marketplace menu.
To customize the marketplace stage:
1.	From the Marketplace list, select the marketplace for which you want to customize the stage. 
The list contains all marketplaces to which you have access as a marketplace manager.
2.	Select the Language for which you want to provide a customized stage. 
You can provide a stage for all supported languages.
3.	Enter the HTML code referencing the desired image. If you do not specify an image for a certain language, the stage _**and mobile stage**_ of the default language is used. If there is no customized stage for the default language either, the default image as available after installation of the platform is used. 
The recommended width of the stage is 100%, the recommended height is between 200 and 300 pixels. 
Example: <IFRAME FRAMEBORDER\="0" SRC\="yourstage.htm" NAME\="stage" WIDTH\="100%" HEIGHT\="280px" SCROLLING\="no"></IFRAME> 

**_The recommended width of the mobile stage is 100%, the recommended height is between 680 and 720 pixels. 
Example: <IFRAME FRAMEBORDER\="0" SRC\="yourstage.htm" NAME\="stage" WIDTH\="100%" HEIGHT\="700px" SCROLLING\="no"></IFRAME>_** 

You can enter the HTML code directly, or you can use an inline frame for embedding the stage in the HTML code of the marketplace home page.
Caution: It is recommended that you use an inline frame. If you do not use an inline frame, specify only snippets as HTML code. Do not use a fully featured HTML page that contains elements like <html>, <head>,or <body>. Check the page layout with the preview function (see next step below). A snippet may break the layout of the marketplace home page, the preview dialog, or even the Customize stage page, especially if the snippet contains scripts (e.g. JavaScripts). 
Be aware that you are responsible for a correct page layout.
4.	Click Preview to view the changed marketplace home page. 
5.	If you have reached the desired result, confirm the publishing of the new marketplace home page by clicking Yes. The new stage is visible to visitors the next time they access your marketplace. 
By clicking No, you return to the Customize stage page and can make additional changes. The existing stage is not changed. 
**_By clicking the Save button, the stage and mobile stage will be saved._** 


The italic and bold text is new.
The mobile stage provide a stage for the mobile few. It can be customized as well es the stage. If the save button is used, both staged will be safed.

**Comment by SuessI** [comment]
@GoebelL @cworf91 @farmakiG 

Is there a fixed size for the mobile image like there is now for the desktop image? See https://github.com/servicecatalog/oscm/issues/745 about this

**Comment by cworf91** [comment]
Please note that the image must be of size 768x 940 pixels. More importent is the aspect ratio of die image. If the display becomes less than 768 pixels, the view switches to the mobile stage.

**Comment by SuessI** [comment]
Documentation updated and distributed for review:

**Customizing the marketplace stage**
On the Customize stage page, you can customize the area of the marketplace home page where you can place, for example, advertisements, eye catchers, or further information.

The marketplace stage can be provided as an image or as HTML code linking, for example, to animations. A separate stage can be used for desktop and mobile devices in each of the supported languages. A preview function allows you to view a stage before it is published. As soon as you confirm the preview, the stage is published and visible to all visitors of the marketplace.

The branding of a marketplace also comprises its layout (colors, fonts, background images, logos, etc.) and the texts (labels of user interface elements, email message texts, etc.). The layout can be customized using the Customize layout menu option in the Marketplace menu. The texts can be customized using the Customize texts menu option in the Marketplace menu.

To customize the marketplace stage:

1. From the Marketplace list, select the marketplace for which you want to customize the stage.
The list contains all marketplaces to which you have access as a marketplace manager.

2. Select the Language for which you want to provide a customized stage.
You can provide stages for all supported languages. If you do not specify a stage for a certain language, the stage of the default language is used. If there is no customized stage for the default language, the initial stage as available after installation of the platform is used.

3. Enter the HTML code referencing the desired stage image. For optimum display, you can specify different stage images for desktop and mobile devices. The stage image for desktop devices is used when the display is wider than 768 pixels. For smaller widths, the stage image for mobile devices is used.

As common with website banners, the image for desktop devices must have a size of 1600 x 500 pixels or multiples thereof with the same aspect ratio. The image for mobile devices must have a size of 768 x 940 pixels or multiples thereof with the same aspect ratio. The recommended width of the stage is 100%. The recommended height is between 200 and 300 pixels for the desktop stage, and between 680 and 720 pixels for the mobile stage.

You can enter the HTML code directly, or you can use an inline frame for embedding the stage in the HTML code of the marketplace home page.

Example:

<iframe FRAMEBORDER="0" width="100%" height="290px" marginwidth="0" marginheight="0" SRC="mystage.htm" SCROLLING="no"></iframe>

Caution: It is recommended that you use an inline frame. If you do not use an inline frame, specify only snippets as HTML code. Do not use a fully featured HTML page that contains elements like <html>, <head>, or <body>. Check the page layout with the preview function (see next step below). A snippet may break the layout of the marketplace home page, the preview dialog, or even the Customize stage page, especially if the snippet contains scripts (e.g. JavaScripts).

Be aware that you are responsible for a correct page layout.

4. Click Preview to view the marketplace home page with the given stage.

5. If the result is as desired, confirm the publishing of the new marketplace home page by clicking Yes. The new stage is visible to visitors the next time they access your marketplace.
By clicking No, you return to the Customize stage page and can make additional changes. The existing stage is not changed.

6. Click Save to save all the changes you have made. Changed stages will be published and be visible to visitors the next time they access the marketplace.

**Comment by SuessI** [comment]
Documentation completed and reviewed.
Removing myself as assignee.
